### ISSUE TITLE
Arc apps on Ansible don't ever clear the LEDs

### ISSUE THREAD

**Issue by AaronMeyers** [monome/libavr32#35]
I just noticed that with the latest libavr32, the arc apps (Cycles, Levels) on Ansible seem to never clear the LEDs which makes them pretty much impossible to use. I managed to track down the commit where it starts happening: https://github.com/monome/libavr32/commit/89291aaabed0b4b25d9862675f76d1f0655600f6

i couldn't build from the two commits from @boqs before that because the compiler had some errors, but the issue wasn't present before those commits.

Maybe it has something to do with this commit? https://github.com/monome/libavr32/commit/c5a6cb14154b2ce182162d321ba5199e90b95b90

**Comment by scanner-darkly** [comment]
yeah, this is due to https://github.com/monome/libavr32/commit/c5a6cb14154b2ce182162d321ba5199e90b95b90 change. 

this line doesn't have the intended effect anymore:
https://github.com/monome/ansible/blob/master/src/ansible_arc.c#L932

it should be changed to `memset(monomeLedBuffer,0,sizeof(MONOME_MAX_LED_BYTES));`

there are several places in there that need to be changed. `ansible_grid.c` from a quick look just uses `128` but i would check it as well.

**Comment by tehn** [comment]
fixed by https://github.com/monome/ansible/pull/30
